import { decideArchitecture, interpretBooleanish } from "./architecture";
import { WizardMode, WizardState, WizardStep } from "./types";

function needsCredentials(state: WizardState) {
  const architecture = decideArchitecture(state);
  return (
    architecture.needsBackend ||
    architecture.needsApiKeys ||
    architecture.needsPayments ||
    architecture.needsFileStorage
  );
}

function shouldAskBackendPreference(state: WizardState) {
  const architecture = decideArchitecture(state);
  return architecture.recommendation !== "local-only";
}

function shouldAskApiExamples(state: WizardState) {
  return interpretBooleanish(String(state.answers.externalApiNeed ?? "")) === "yes";
}

export const FLOW_ORDER: Array<Exclude<WizardMode, "review" | "build">> = [
  "product",
  "features",
  "integrations",
  "ui",
  "credentials",
];

export const WIZARD_STEPS: WizardStep[] = [
  {
    id: "app-name",
    mode: "product",
    label: "App name",
    field: "appName",
    prompt: "What should this mobile app be called?",
    help: "A working name is enough for now.",
    required: true,
  },
  {
    id: "one-line-summary",
    mode: "product",
    label: "One-line summary",
    field: "oneLineSummary",
    prompt: "In one simple sentence, what should the app do?",
    help: "Explain it like you are pitching it to a friend.",
    required: true,
  },
  {
    id: "target-users",
    mode: "product",
    label: "Target users",
    field: "targetUsers",
    prompt: "Who is this app mainly for?",
    help: "Examples: busy parents, agency owners, clinic staff, students.",
    required: true,
  },
  {
    id: "problem",
    mode: "product",
    label: "Problem",
    field: "problem",
    prompt: "What problem are these users dealing with?",
    help: "Keep it practical and non-technical.",
    required: true,
  },
  {
    id: "solution",
    mode: "product",
    label: "Solution",
    field: "solution",
    prompt: "How should the app solve that problem?",
    help: "Focus on the result the user gets.",
    required: true,
  },
  {
    id: "app-type",
    mode: "product",
    label: "App type",
    field: "appType",
    prompt: "What kind of app is this?",
    help: "Examples: habit tracker, planner, booking app, team portal, school app.",
    required: true,
  },
  {
    id: "core-features",
    mode: "features",
    label: "Core features",
    field: "coreFeatures",
    prompt: "What are the must-have features for version one?",
    help: "List them with commas or short lines.",
    required: true,
    list: true,
  },
  {
    id: "offline-sync-expectation",
    mode: "features",
    label: "Offline or sync expectation",
    field: "offlineSyncExpectation",
    prompt: "Should the app work only on one device, stay available offline, or sync across devices too?",
    help: "Simple wording is fine, like 'offline only' or 'needs sync across devices'.",
    required: true,
  },
  {
    id: "user-access-model",
    mode: "features",
    label: "Single-user or shared usage",
    field: "userAccessModel",
    prompt: "Will this app be used by one person for their own data, or by multiple people sharing data?",
    help: "Examples: single user, parent and child, staff team, customers and admin.",
    required: true,
  },
  {
    id: "roles",
    mode: "features",
    label: "Roles",
    field: "roles",
    prompt: "What user roles should exist in the app?",
    help: "Examples: member, admin, coach, client, staff.",
    required: true,
    list: true,
  },
  {
    id: "required-screens",
    mode: "features",
    label: "Required screens",
    field: "requiredScreens",
    prompt: "Which main screens should the mobile app include?",
    help: "Examples: onboarding, dashboard, tasks, profile, settings, checkout.",
    required: true,
    list: true,
  },
  {
    id: "notifications-need",
    mode: "features",
    label: "Notifications",
    field: "notificationsNeed",
    prompt: "Should the app send reminders or push notifications?",
    help: "A simple yes or no is enough.",
    required: true,
  },
  {
    id: "payments-need",
    mode: "features",
    label: "Payments",
    field: "paymentsNeed",
    prompt: "Does the app need payments, subscriptions, or purchases?",
    help: "A simple yes or no is enough.",
    required: true,
  },
  {
    id: "login-need",
    mode: "integrations",
    label: "Login need",
    field: "loginNeed",
    prompt: "Do people need to sign in with an account?",
    help: "Simple answers like yes, no, or maybe later are fine.",
    required: true,
  },
  {
    id: "admin-need",
    mode: "integrations",
    label: "Admin access",
    field: "adminNeed",
    prompt: "Should there be an admin or staff-only area?",
    help: "Just answer yes or no.",
    required: true,
  },
  {
    id: "file-upload-need",
    mode: "integrations",
    label: "File uploads",
    field: "fileUploadNeed",
    prompt: "Will users upload files, photos, or documents?",
    help: "Just answer yes or no.",
    required: true,
  },
  {
    id: "external-api-need",
    mode: "integrations",
    label: "External APIs",
    field: "externalApiNeed",
    prompt: "Does the app need any outside APIs or third-party services?",
    help: "Examples: maps, weather, AI, payment, SMS, calendar, delivery tracking.",
    required: true,
  },
  {
    id: "backend-preference",
    mode: "integrations",
    label: "Backend preference",
    field: "backendPreference",
    prompt: "If this app needs cloud support, would you like a simple backend like Supabase?",
    help: "If you're unsure, saying 'Supabase is fine' is perfect.",
    required: true,
    shouldAsk: shouldAskBackendPreference,
  },
  {
    id: "api-examples",
    mode: "integrations",
    label: "API examples",
    field: "apiExamples",
    prompt: "Which outside APIs or services should the app connect to?",
    help: "List only the ones you already know about.",
    required: true,
    list: true,
    shouldAsk: shouldAskApiExamples,
  },
  {
    id: "billing-model",
    mode: "features",
    label: "Billing model",
    field: "billingModel",
    prompt: "If there is money involved, how should the app charge or earn?",
    help: "Examples: free, subscription, one-time purchase, service lead generation.",
    required: true,
  },
  {
    id: "mvp-scope",
    mode: "features",
    label: "MVP scope",
    field: "mvpScope",
    prompt: "What absolutely needs to be in the first mobile release?",
    help: "Keep the first release focused and realistic.",
    required: true,
  },
  {
    id: "future-scope",
    mode: "features",
    label: "Future scope",
    field: "futureScope",
    prompt: "What can wait until after the MVP is live?",
    help: "Add stretch ideas or phase-two features here.",
    required: true,
  },
  {
    id: "special-instructions",
    mode: "features",
    label: "Special instructions",
    field: "specialInstructions",
    prompt: "Any special rules, constraints, or launch notes we should remember?",
    help: "You can mention audience concerns, brand rules, or launch timing.",
    required: true,
  },
  {
    id: "theme-mode",
    mode: "ui",
    label: "Theme mode",
    field: "themeMode",
    prompt: "Should the UI feel light, dark, or mixed?",
    help: "Choose the overall visual mood for the mobile app.",
    required: true,
  },
  {
    id: "design-preference",
    mode: "ui",
    label: "Design preference",
    field: "designPreference",
    prompt: "What design style do you want?",
    help: "Examples: minimal, luxury, playful, business, premium, bold.",
    required: true,
  },
  {
    id: "preferred-colors",
    mode: "ui",
    label: "Preferred colors",
    field: "preferredColors",
    prompt: "Which colors or mood should the UI lean toward?",
    help: "Examples: soft neutrals, energetic orange, calm blue and cream.",
    required: true,
  },
  {
    id: "icon-style",
    mode: "ui",
    label: "Icon style",
    field: "iconStyle",
    prompt: "What icon style do you prefer?",
    help: "Examples: rounded, outlined, bold, playful, simple.",
    required: true,
  },
  {
    id: "layout-style",
    mode: "ui",
    label: "Layout style",
    field: "layoutStyle",
    prompt: "Should the app feel dashboard-heavy or more like a simple guided flow?",
    help: "Pick the interaction style that matches the app.",
    required: true,
  },
  {
    id: "navigation-style",
    mode: "ui",
    label: "Navigation style",
    field: "navigationStyle",
    prompt: "Do you prefer bottom tabs, a simple stack flow, or something else?",
    help: "Mobile-first navigation choices are enough here.",
    required: true,
  },
  {
    id: "animation-preference",
    mode: "ui",
    label: "Animation preference",
    field: "animationPreference",
    prompt: "Should the app feel calm, lively, or mostly static?",
    help: "This helps shape motion and transitions.",
    required: true,
  },
  {
    id: "interaction-style",
    mode: "ui",
    label: "Interaction style",
    field: "interactionStyle",
    prompt: "What should mobile interactions feel like?",
    help: "Examples: fast and minimal, friendly and guided, premium and smooth.",
    required: true,
  },
  {
    id: "accessibility-preferences",
    mode: "ui",
    label: "Accessibility preferences",
    field: "accessibilityPreferences",
    prompt: "Any accessibility or readability preferences we should prioritize?",
    help: "Examples: larger text, stronger contrast, simpler labels, reduced motion.",
    required: true,
  },
  {
    id: "credentials-owner",
    mode: "credentials",
    label: "Credentials owner",
    field: "credentialsOwner",
    prompt: "Who will be responsible for app credentials, accounts, and store access?",
    help: "Examples: founder, agency, product manager, client team.",
    required: true,
    shouldAsk: needsCredentials,
  },
  {
    id: "credentials-status",
    mode: "credentials",
    label: "Credentials status",
    field: "credentialsStatus",
    prompt: "Which accounts or credentials already exist, and which still need to be created?",
    help: "Do not paste secrets. A simple checklist status is enough.",
    required: true,
    shouldAsk: needsCredentials,
  },
  {
    id: "third-party-keys",
    mode: "credentials",
    label: "Third-party keys",
    field: "thirdPartyKeys",
    prompt: "Which outside services will need keys, tokens, or account access?",
    help: "Examples: Supabase, Stripe, Firebase, Google Maps, OpenAI.",
    required: true,
    list: true,
    shouldAsk: needsCredentials,
  },
  {
    id: "ui-refresh-notes",
    mode: "ui",
    label: "UI refresh notes",
    field: "uiRefreshNotes",
    prompt: "What would you like to refine or change about the UI preferences?",
    help: "Use this later for design updates without changing product info.",
    required: false,
    allowsMultipleRuns: true,
  },
];
